# Generated by Django 5.0.3 on 2024-03-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_funcionario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Genero',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name_plural': 'Generos'},
        ),
    ]
